// SIET private limited is all set to begin a new academic year with a bunch of talents. They need to give employee ids to all the freshers of all team. The employee id is generated by using the training id of the employees which was given at the time of training. Help the company in generating employee id by developing a java application

// Requirements:
// -The training id should  only contain 9 digits, otherwise  print "<training id> is an invalid training id" and terminate the application
// -The first 4 digits in the training id represent year in which people got trained(it should be 2021), if not print "<year> is an invalid year" and terminate the application
// -The 5th and 6th digits represent team codes
//  01 - LP
//  02 - TA
//  03 - CT
//  04 - PT
//  05 - TT
// -Any other digits than the above mentioned one is given then print "<code> is an invalid team code"  and terminate the application
// -The last 3 digits should be the employees roll number starting from 001 to 999, if not print  "<roll no> is an invalid roll number" and terminate the application.
// -The generated employee id should be 9 characters long with the first 4 letters as SIET, the next two letters can be LP/TA/CT/PT/TT depending on the team code in the training id and the last 3 digits should be the employee's roll number.
// - The trainingId is validated in accordance with the prescribed order.
// [i.e when 1 or more validation rules gets violated , the first violation message gets displayed. Refer sample output]

// Note:

//        In the Sample Input / Output provided, the highlighted text in bold corresponds to the input given by the user, and the rest of the text represents the output.
//        Ensure to follow the object-oriented specifications provided in the question description.
//        Ensure to provide the names for classes, attributes, and methods as specified in the question description.
//       Adhere to the code template, if provided
// Please do not use System.exit(0) to terminate the program.

import java.util.Scanner;

public class EmployeeIdGenerartion 
{
	public static void main(String args[]) 
	{
	
		Scanner sc =new Scanner(System.in);
		//Fill the code
		System.out.println("Enter the training id");
		long id=sc.nextLong();
		
		//validate id
		if(id<100000000 || id>999999999) {
			System.out.println(id+" is an invalid training id");
			return;
		}
		
		//convert id to string for easier extractions
		String idInString=id+"";
		
		//extracting year
		String yearInString=idInString.substring(0,4);
		
		int year=Integer.parseInt(yearInString);
		
		if(year!=2021) {
			System.out.println(year+" is an invalid year");
			return;
		}
		
		
		//extractcing team code which is a number
		String teamCodeFromId=idInString.substring(4,6);
		String teamCode="";
		
		//converting the team code into alphabet
		switch(teamCodeFromId) {
		case "01" -> teamCode="LP";
		case "02" -> teamCode="TA";
		case "03" -> teamCode="CT";
		case "04" -> teamCode="PT";
		case "05" -> teamCode="TT";
		default->{
			System.out.println(teamCodeFromId+" is an invalid team code"); 
			return;
		}
	}
		
	//extracting emp roll based on position 5th and 6th
	String empRollFromId=idInString.substring(6,9);
	
	if(empRollFromId.length()!=3 || empRollFromId.equals("000")) {
		System.out.println(empRollFromId+" is an invalid roll number");
		return;
	}
	
	//generating the emp id
	String empId=generateEmpId(teamCode,empRollFromId);
	System.out.println("Employee Id: "+empId);
		
		}
		
		static String generateEmpId(String teamCode,String empRollFromId) {
			String id="SIET";
			id+=teamCode+empRollFromId;
			return id;
		}
	}
	
	

